"""
Demo data — real news articles for El Sauzal / Ensenada, March 2026.
"""


def get_demo_articles() -> list[dict]:
    return [
        {
            "id": "demo_sec_01",
            "title": "Ensenada despliega 365 elementos para operativo Semana Santa 2026",
            "description": "El Gobierno de Ensenada puso en marcha el Operativo Vacacional Semana Santa 2026 con 365 elementos y 120 unidades para vigilar carreteras, playas y zonas serranas.",
            "url": "https://www.ensenadanoticias.com/ensenada/2026/03/24/ensenada-despliega-365-elementos-para-operativo-semana-santa-2026/",
            "source": "Ensenada Noticias",
            "published_at": "2026-03-24T10:00:00Z",
            "fetched_from": "demo",
            "category": "seguridad",
            "relevance_score": 9,
            "summary_es": "Ensenada despliega 365 elementos de seguridad para operativo Semana Santa 2026 — vigilancia en carreteras, playas y zonas serranas hasta el 12 de abril",
            "is_relevant": True,
        },
        {
            "id": "demo_sec_02",
            "title": "Ex militar detenido por lanzar bombas molotov a empresa de mariscos en El Sauzal",
            "description": "Un ex militar identificado como Virgilio, de 34 años, fue detenido por lanzar bombas molotov a una empresa de mariscos en El Sauzal, Ensenada.",
            "url": "https://zetatijuana.com/category/ensenada/",
            "source": "Semanario ZETA",
            "published_at": "2026-03-03T14:30:00Z",
            "fetched_from": "demo",
            "category": "seguridad",
            "relevance_score": 9,
            "summary_es": "Ex militar detenido tras lanzar bombas molotov a empresa de mariscos en El Sauzal — sospechoso de 34 años",
            "is_relevant": True,
        },
        {
            "id": "demo_sec_03",
            "title": "Marina apoya a bomberos en control de incendio en El Sauzal, Ensenada",
            "description": "Conato de incendio en predio de la empresa MPS, dedicada a la recepción de residuos de la industria marítima en El Sauzal.",
            "url": "https://www.uniradiobaja.com/gobierno/marina-apoya-bomberos-control-incendio-sauzal-ensenada-n871091",
            "source": "Uniradio Baja California",
            "published_at": "2026-03-18T11:00:00Z",
            "fetched_from": "demo",
            "category": "seguridad",
            "relevance_score": 8,
            "summary_es": "Marina mexicana apoyó a bomberos en control de incendio en planta de residuos marítimos MPS en El Sauzal",
            "is_relevant": True,
        },
        {
            "id": "demo_sec_04",
            "title": "Pentágono advierte riesgo de violencia de cárteles para turistas en México antes del Mundial 2026",
            "description": "Fuerzas especiales del Pentágono advierten que la violencia de los cárteles representa un riesgo para residentes y turistas.",
            "url": "https://www.nmas.com.mx/nacional/pentagono-advierte-riesgo-carteles-mundial-2026/",
            "source": "N+ Noticias",
            "published_at": "2026-03-19T16:00:00Z",
            "fetched_from": "demo",
            "category": "seguridad",
            "relevance_score": 7,
            "summary_es": "Pentágono advierte riesgo de violencia de cárteles para turistas en México antes del Mundial 2026",
            "is_relevant": True,
        },
        {
            "id": "demo_pol_01",
            "title": "Agenda política de México 2026: reformas, elecciones y proyectos clave",
            "description": "Los verdaderos partidos de 2026 se jugarán en la agenda política.",
            "url": "https://elcongresista.mx/politica/agenda-politica-de-mexico-en-2026/",
            "source": "El Congresista",
            "published_at": "2026-03-18T08:00:00Z",
            "fetched_from": "demo",
            "category": "general",
            "relevance_score": 6,
            "summary_es": "Agenda política de México 2026: reformas constitucionales, elecciones intermedias y proyectos clave",
            "is_relevant": True,
        },
        {
            "id": "demo_pol_02",
            "title": "Zona Sísmica: alerta en Baja California por actividad tectónica",
            "description": "Expertos advierten sobre la actividad sísmica en Baja California, incluyendo la falla de San Andrés.",
            "url": "https://www.elimparcial.com/mxl/columnas/2026/03/03/zona-sismica/",
            "source": "El Imparcial",
            "published_at": "2026-03-03T09:00:00Z",
            "fetched_from": "demo",
            "category": "general",
            "relevance_score": 7,
            "summary_es": "Alerta sísmica en Baja California — expertos advierten sobre actividad tectónica incrementada cerca de Ensenada",
            "is_relevant": True,
        },
        {
            "id": "demo_evt_01",
            "title": "Gran Carnaval de Ensenada 2026: del 12 al 17 de marzo en Playa Hermosa",
            "description": "El Gran Carnaval de Ensenada se celebra del 12 al 17 de marzo con más de 400,000 asistentes.",
            "url": "https://www.uniradiobaja.com/gobierno/ensenada-gran-carnaval-2026",
            "source": "Uniradio Baja California",
            "published_at": "2026-03-12T12:00:00Z",
            "fetched_from": "demo",
            "category": "eventos",
            "relevance_score": 9,
            "summary_es": "Gran Carnaval de Ensenada 2026: 12-17 de marzo en Playa Hermosa — se esperan más de 400,000 visitantes",
            "is_relevant": True,
        },
        {
            "id": "demo_evt_02",
            "title": "Fiestas de la Vendimia 2026: del 5 al 23 de agosto en Valle de Guadalupe",
            "description": "La tradicional Fiesta de la Vendimia de Ensenada celebra la cosecha de vid.",
            "url": "https://www.zonaturistica.com/eventos-en/baja-california/ensenada",
            "source": "Zona Turística",
            "published_at": "2026-03-20T10:00:00Z",
            "fetched_from": "demo",
            "category": "eventos",
            "relevance_score": 7,
            "summary_es": "Fiestas de la Vendimia 2026 en Valle de Guadalupe: 5-23 de agosto — Ensenada produce el 70% del vino mexicano",
            "is_relevant": True,
        },
        {
            "id": "demo_evt_03",
            "title": "La Baja 1000 Rally 2026: del 3 al 7 de junio",
            "description": "Más de 250 vehículos competirán en un rally de 500 kilómetros.",
            "url": "https://www.bajacalifornia.travel/en/eventos",
            "source": "Baja California Travel",
            "published_at": "2026-03-15T08:00:00Z",
            "fetched_from": "demo",
            "category": "eventos",
            "relevance_score": 6,
            "summary_es": "Rally Baja 1000 en 2026: 3-7 de junio — más de 250 vehículos en carrera de 500 km por la zona",
            "is_relevant": True,
        },
        {
            "id": "demo_trf_01",
            "title": "Operativo vial Semana Santa: refuerzan vigilancia en carretera Ensenada-Tijuana",
            "description": "Autoridades refuerzan vigilancia en la carretera escénica Ensenada-Tijuana.",
            "url": "https://www.ensenadanoticias.com/ensenada/",
            "source": "Ensenada Noticias",
            "published_at": "2026-03-24T07:00:00Z",
            "fetched_from": "demo",
            "category": "trafico",
            "relevance_score": 9,
            "summary_es": "Operativo vial Semana Santa: refuerzan vigilancia en carretera Ensenada-Tijuana por tráfico esperado",
            "is_relevant": True,
        },
        {
            "id": "demo_trf_02",
            "title": "Tren Lechería-AIFA inicia operaciones a finales de marzo",
            "description": "El tren de pasajeros Lechería-AIFA comenzará operaciones. BC sigue sin proyecto ferroviario.",
            "url": "https://www.milenio.com/politica/tren-lecheria-aifa-marzo-2026",
            "source": "Milenio",
            "published_at": "2026-03-18T14:00:00Z",
            "fetched_from": "demo",
            "category": "trafico",
            "relevance_score": 4,
            "summary_es": "Tren Lechería-AIFA inicia operaciones — Baja California sigue sin proyecto ferroviario propio",
            "is_relevant": True,
        },
        {
            "id": "demo_biz_01",
            "title": "Ensenada: Capital del Vino de México con más del 70% de producción nacional",
            "description": "Ensenada se consolida como la Capital del Vino de México con sus 7 valles.",
            "url": "https://www.bajacalifornia.travel/en/destinos/ensenada",
            "source": "Baja California Travel",
            "published_at": "2026-03-21T10:00:00Z",
            "fetched_from": "demo",
            "category": "competencia",
            "relevance_score": 8,
            "summary_es": "Ensenada — Capital del Vino de México: 7 valles producen el 70% del vino nacional",
            "is_relevant": True,
        },
        {
            "id": "demo_biz_02",
            "title": "México presenta plan de US$22.6 mil millones para modernización de carreteras",
            "description": "Plan de inversión para modernización de autopistas, incluyendo rutas de Baja California.",
            "url": "https://mexicobusiness.news/automotive/news/mexico-highway-plan",
            "source": "Mexico Business News",
            "published_at": "2026-03-17T10:00:00Z",
            "fetched_from": "demo",
            "category": "trafico",
            "relevance_score": 6,
            "summary_es": "México presenta plan de US$22.6 mil millones para modernizar carreteras — incluye rutas de Baja California",
            "is_relevant": True,
        },
        {
            "id": "demo_gen_01",
            "title": "Turismo en Ensenada 2026: ruta del vino, gastronomía y avistamiento de ballenas",
            "description": "Ensenada se posiciona como destino turístico.",
            "url": "https://www.expedia.com/Ensenada",
            "source": "Expedia",
            "published_at": "2026-03-22T08:00:00Z",
            "fetched_from": "demo",
            "category": "eventos",
            "relevance_score": 5,
            "summary_es": "Turismo en Ensenada 2026: ruta del vino, gastronomía de mariscos, avistamiento de ballenas y cultura local",
            "is_relevant": True,
        },
        {
            "id": "demo_gen_02",
            "title": "Eventos del Mundial 2026: Baja California como zona de paso para fans",
            "description": "Baja California se prepara para recibir fans que cruzarán la frontera desde Tijuana.",
            "url": "https://www.nmas.com.mx/nacional/que-va-a-pasar-en-2026-en-mexico/",
            "source": "N+ Noticias",
            "published_at": "2026-03-20T14:00:00Z",
            "fetched_from": "demo",
            "category": "eventos",
            "relevance_score": 7,
            "summary_es": "Mundial 2026: Baja California se prepara para flujo de fans que cruzarán la frontera desde Tijuana",
            "is_relevant": True,
        },
    ]
